sudo: false
language: node_js
node_js:
- '9'
install:
- echo "skip install"
script:
- npm test
- git checkout master
- npm version patch -m "Bump version [ci skip]"
- git remote add upstream https://${GH_TOKEN}@github.com/umijs/es5-imcompatible-versions.git
- git config --global user.email "deploy@travis-ci.org"
- git config --global user.name "Deployment Bot (from Travis CI)"
- git push upstream master --tags
deploy:
  provider: npm
  email: yesmeck@gmail.com
  api_key:
    secure: dWVNurii52BAfmG8Pazf1Go1RnJ6G24bq+Zm1giLdAFjxaWo48etpud65H+WX8GV/EAIiYxRSFGCO4+MrYoo9AL9iH4oGiJZLZQ02uuKhZM4C0uVbu4adH94mAPzqKrT6mPDidzZn0wfssYr6U4HNEfOsstg4mW8XCBi46+ipqzs0LZSRVOl/VRr/Ygdk+/ULmuegsALM/R7v8gI+YEz4cl3x0QFikFJEDDgg1D3aVAKlu/0isNBxeVj38O8CyV01Ur1rC+38ZaXb8bOpcPYx/+ZM76zizULZlbbkfiw8o5ikJIAk2O/9dc3uxQKiDbOg5yR1pest/kKKMUZGUcICaCQHeIX2r65D8x9abiUTchOXoXENjdYqUA6bABC49/57hzPbXo8ur8wahjjsUzlQnp0U050BxR+bg3NXtgsSC8rPhzEnpdzTkgh9BfTtND8g8pmMyg1LtCIxxwTIVE3KKMxbTudUwA3QOicLziWvw0PdnBWDkyOvf1iEJI96LGjNxq7A4aKHqnBk6QJIcjpYOAyW45mUpG9M1a7vjgjfM+2HZOH2ggKNuArJyXghGamkLWEHO+Z2QM3jDGoRxaXFlVfOKeKVsppg6iQT9tTjPTbQD7pLXgOtJ/Xjq76GSm9IajkxiO1dJjgUxP4q5TV0Vcu8bHgS2DAOXGtfmJr+Jo=
  on:
    repo: umijs/es5-imcompatible-versions
