sudo: false
language: node_js
node_js:
- '9'
install:
- echo "skip install"
script:
- npm test
- git checkout master
- npm version patch -m "Bump version [ci skip]"
- git remote add upstream https://${GH_TOKEN}@github.com/umijs/es5-imcompatible-versions.git
- git config --global user.email "deploy@travis-ci.org"
- git config --global user.name "Deployment Bot (from Travis CI)"
- git push upstream master --tags
deploy:
  provider: npm
  email: yesmeck@gmail.com
  api_key:
    secure: HJmXj7EdnwpTRBnvMS+ck5dPtyX70Ik5lonowJmoKimBzSREqTsgSnZM90NAXvD6ixrY14SITmoXQzN28dCWs4bZG/cthwzBql2HsiH8DwJ4143QWhytjp9ZPPN5L1BlrgWWQtE7SYy8xrtdkCB+zwThpdAxvwG5L1adzmwDLdWHKeQbAa+UCVKUQ6voqqmHAtupQQ8rduE5qSPQFfetkeugP5DnokLKBRmlFqXgVsnWNYJhN0mIrY0ncDWs5MqHihOiQDAy0jyNNbz0DGZr+9GqXwxDqPWSDp41rF14QlIonsrRqovttmFCbp3CWl32qTSkwM2ffoXpgqXWWzEmakWaXFuJ2uldYe/YmZVMt6wLdHboK2E1BOosLdLg/mRGCjVQXo3R/zUS0PCpEizDkNnOwefC15wp4Dy8JbKDX6L5LthI630UKnUcLfcxP0zPur8EDAzZJuasX17qQSBIkczLUav7RrHYvfGeaTyo7DO9HrTAnygR/OUso6i4g5YzETRl5WyEcDKcjq7Vixm1HwR5z5nfxvDZtrcbnpxrOg3qc/hwwtLE7B0d4S3mEOnpi5v2hcT2NcIGsGMj4qZI1CTyUYOXyRfx7NZq8HK0jw5qVaNUf74r7XuWcn2Cc0ItVe5YUKE2fD34tn3zfIdv75bd3cW28NGxeyRnXzPtb6E=
  on:
    repo: umijs/es5-imcompatible-versions
